apiVersion: apps/v1
kind: Deployment
metadata:
  name: safari-deployment
  labels:
    app: safari
spec:
  replicas: 3
  selector:
    matchLabels:
      app: safari
  template:
    metadata:
      labels:
        app: safari
    spec:
      containers:
      - name: safari
        image: httpd:2.4.41-alpine
        ports:
        - containerPort: 80
