apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground
spec:
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    ports:
    - containerPort: 80
    env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
    volumeMounts:
    - mountPath: /usr/local/bin
      name: log-volume
  - name: c2
    image: busybox:1.31.1
    command: [ "sh", "-c"]
    args:
    - while true; do date >> /usr/local/bin/date.log; sleep 1;
      done
    volumeMounts:
    - mountPath: /usr/local/bin
      name: log-volume
  - name: c3
    image: busybox:1.31.1
    command: [ "sh", "-c"]
    args: ["tail -f /usr/local/bin/date.log"]
    volumeMounts:
    - mountPath: /usr/local/bin
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir:
      sizeLimit: 1000Mi
